spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: citronix
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml