spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/JenkinsDb
    username: JenkinsDb
    password: JenkinsDb
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml